### ISSUE TITLE
Adding `New` label in Site Settings sidebar

### ISSUE THREAD

**Issue by prabhav** [netlify/netlify-emails-plugin#104]
Might be useful to add a `new` label for Emails in the Site settings sidebar panel (like Env vars has in this screenshot). Since this is a new page within Site Settings, we'd want users to be aware about the change.

![image](https://user-images.githubusercontent.com/6019790/199065200-0823bb86-8332-425d-a10b-8e764714d34d.png)

**Comment by lemusthelroy** [comment]
![image](https://user-images.githubusercontent.com/15314252/199225077-84cd1230-68e4-4776-a986-42f901dd6d86.png)
Done!
