### ISSUE TITLE
[UX Flow] Setting up emails — directly in `Edit` mode first?

### ISSUE THREAD

**Issue by prabhav** [netlify/netlify-emails-plugin#105]
When a user clicks Enable emails for the first time, I was wondering if it'd be helpful if we can directly drop them in the `Edit` mode so they don't have to click twice for what might be an obvious first step to set up emails. This might need some discussion/thinking so please let me know how I can support this from a design perspective!

![image](https://user-images.githubusercontent.com/6019790/199065863-c1b28e97-9539-47f0-be81-18600c31d343.png)

**Comment by lemusthelroy** [comment]
Netlify UX has now been updated so that when first enabling the plugin, the user is taken straight to edit mode. There is still improvements we can make here as the user could abandon this process and the plugin is left in an enabled state, without the required configuration.

**Comment by prabhav** [comment]
This is super awesome, feels a lot neater — thanks a bunch Lewis! 💛
