### ISSUE TITLE
[Feature Request]: gmail provider (TLS)

### ISSUE THREAD

**Issue by talves** [netlify/netlify-emails-plugin#113]
It's kinda more than a request. I currently have this solution proofed and working. I forked/cloned the plugin and was able to get gmail up and running as a provider. I'm using port 587 (TLS) which can be used easily if you have gmail setup with 2FA and create an App Key. I believe this is a viable solution including a free account, this gives a user up to 500 emails a day. If they are a paid account they get up to 2000 per day as of this writing.

I'm wondering if this is something Netlify would consider for this plugin.

**Comment by lemusthelroy** [comment]
Hi @talves, thanks for the feature request. Requests of this nature are certainly something we will continue to monitor as we want to see how this feature gets used by our users and what integrations we can create that will best serve them.

That said, we are for now, looking to target the top transactional email API providers - which Gmail doesn't really fall into. These choices tend to be guided by looking at data telling us what packages we see our developers installing on their Netlify sites and what the community consider the top email API providers.

I hope the above provides some clarity, but we will certainly keep monitoring what users are asking for.

**Comment by talves** [comment]
Interesting take. I host my domains at google domains because they allow me to alias my domain emails to my gmail account. Being able to send an email and have it show up in a `sent` box is actually pretty powerful IMO. 

Anyone who needs this solution can easily set it up, so not really a big loss.

This plugin and the dev site preview of the email form template was a nice solution. Good job.

Have a good day,
T
