### ISSUE TITLE
Error "Email templates directory ./emails does not exist" in monorepo environment

### ISSUE THREAD

**Issue by awesomephant** [netlify/netlify-emails-plugin#135]
I can't get this plugin to work on a site that's deployed from a monorepo. My repo contains two separate sites and looks like this:

```
websites
├─ site-a
├─ site-b
    ├─ netlify.toml
    ├─ emails/welcome
    │   ├─ index.html
    ├─ netlify/functions
        ├─ sendWelcome.ts 
```

`sendWelcome.ts` is triggered from the frontend and makes a POST request to `${process.env.URL}/.netlify/functions/emails/welcome` to send an email via Sendgrid, just like [in the docs](https://docs.netlify.com/integrations/email-integration/#trigger-an-email-from-your-code).

When I run the project locally (via `netlify dev`) this works as expected, but on the live site the call to the email handler fails with `Email templates directory ./emails does not exist`. I've tried setting `NETLIFY_EMAILS_DIRECTORY` to different values and including the email templates manually via an `included_files` directive in my `netlify.toml`, but to no avail.

Finally I tried to access the email templates from `sendWelcome.ts` using `fs.existsSync()`, which failed as well. This makes me think there might be a problem with the `included_files` directive in monorepos, but maybe I'm missing something simpler?

See also [this thread](https://answers.netlify.com/t/netlify-email-fetch-returning-error404-or-net-err-failed-when-removed/84150/7).

**Comment by lemusthelroy** [comment]
Just so that you are aware, at the end of this week we will be removing this repository, as the codebase for this integration now lives elsewhere.

As we are proactively discussing this issue currently in the forum and we are tracking the issue internally, I'm going to close this issue ahead of us removing this repository.
